### ISSUE TITLE
[1.19.2]: No Roasted Ear recipe? 

### ISSUE THREAD

**Issue by Dejeh** [Chefs-Delight/NethersDelight_Forge#10]
### Description

I saw that there is a roasted hoglin ear png, which might suggest it exists, but the recipe isn't in-game nor does it have a recipe in src.

### Mod list

Nether's delight 1.19-3.0
Farmer's delight 1.19-1.2.0

### Forge

- [X] I am using the Forge version of Nether's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by Umpaz** [comment]
You can get the roasted ear from cutting it off of the stuffed hoglin feast!

**Comment by Dejeh** [comment]
ah. my mistake, i thought they were separate items for some reason.
