### ISSUE TITLE
[1.19.2]: 2 ripening JEI categories instead of 1

### ISSUE THREAD

**Issue by Lykrast** [Chefs-Delight/NethersDelight_Forge#18]
### Description

There are two JEI tabs for ripening, one for Flaxen Cheese and one for Scarlet Cheese. However, they both look exactly the same, so grouping them into one JEI tab that has both "recipes" would be a little better, and it would fit on one screen.

![image](https://user-images.githubusercontent.com/8684850/236770843-0a876829-5f79-422f-ba31-72cd37efbc5b.png) ![image](https://user-images.githubusercontent.com/8684850/236770864-2b5bf144-6aa9-4ea7-9f99-67ff814ce097.png)

### Mod list

* FarmersDelight-1.19-1.2.0
* NethersDelight-1.19-3.0
* jei-1.19.2-forge-11.4.0.286

### Forge

- [X] I am using the Forge version of Nether's Delight

### Minimal instance

- [ ] I have tested this on a minimal instance

### Performance and shader mods

- [X] I have tested this without performance or shader mods

**Comment by Aceplante** [comment]
There is no cheese in this mod?

**Comment by Lykrast** [comment]
Wait... I thought this was the [Brewin' And Chewin'](https://legacy.curseforge.com/minecraft/mc-mods/brewin-and-chewin) issue tracker by the same authors...

And apparently Brewin' and Chewin' doesn't have an issue tracker so uh...

**Comment by Umpaz** [comment]
yes there's not one for BnC yet
